version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - ./data/uber_mongo_db:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  user:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      JWT_SECRET: 123
      MONGO_URL: mongodb://admin:qwerty@mongo:27017/user?authSource=admin
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongo
      - rabbitmq

  captain:
    build: ./captain-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      JWT_SECRET: 123
      MONGO_URL: mongodb://admin:qwerty@mongo:27017/captain?authSource=admin
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongo
      - rabbitmq

  ride:
    build: ./ride-service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      JWT_SECRET: 123
      MONGO_URL: mongodb://admin:qwerty@mongo:27017/ride?authSource=admin
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      BASE_URL: http://gateway:3000
    depends_on:
      - mongo
      - rabbitmq

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      GATEWAY_PORT: 3000
      USER_SERVER: user
      CAPTAIN_SERVER: captain
      RIDE_SERVER: ride
      USER_SERVICE_PORT: 3001
      CAPTAIN_SERVICE_PORT: 3002
      RIDE_SERVICE_PORT: 3003
    depends_on:
      - user
      - captain
      - ride
      - rabbitmq